package com.taxoryn.module.notice.enums;

public enum NoticeActivityType {
    NOTICE_CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ASSIGNMENT_CHANGED,
    RESPONSE_DRAFTED,
    RESPONSE_SUBMITTED_FOR_REVIEW,
    REVISION_REQUESTED,
    RESPONSE_APPROVED,
    RESPONSE_PARTNER_APPROVED,
    RESPONSE_FILED,
    HEARING_SCHEDULED,
    HEARING_OUTCOME_RECORDED,
    DOCUMENT_ATTACHED,
    DOCUMENT_REQUESTED,
    TASK_CREATED,
    NOTICE_CLOSED,
    INTERNAL_NOTE_ADDED
}
