package com.taxoryn.module.reminder.entity;

/**
 * Who should receive the reminder generated by an automation rule.
 */
public enum AutomationTargetType {
    /** The user assigned to the Task. */
    TASK_ASSIGNEE,
    /** The user who owns / manages the Engagement. */
    ENGAGEMENT_OWNER,
    /** The user assigned to the Work Instance. */
    WORK_INSTANCE_ASSIGNEE,
    /** A specific named user (stored separately in the rule or reminder). */
    SPECIFIC_USER
}
