package com.taxoryn.module.udin.model;

/**
 * Standard document types for which UDINs are generated by professionals.
 */
public enum UdinDocumentType {
    TAX_AUDIT_REPORT_3CA_3CD,
    TAX_AUDIT_REPORT_3CB_3CD,
    GST_AUDIT_CERTIFICATE,
    TRANSFER_PRICING_REPORT,
    NET_WORTH_CERTIFICATE,
    TURNOVER_CERTIFICATE,
    FORM_15CB_CERTIFICATION,
    INTERNAL_AUDIT_REPORT,
    STATUTORY_AUDIT_REPORT,
    OTHER_CERTIFICATION,
    OTHER
}
